#! /bin/bash

# https://gist.github.com/vaiorabbit/6204931

RELEASE="3.3.8"

curl -L https://github.com/glfw/glfw/releases/download/${RELEASE}/glfw-${RELEASE}.zip > glfw-${RELEASE}.zip
unzip glfw-${RELEASE}.zip
cd glfw-${RELEASE}/
mkdir build
cd build
export MACOSX_DEPLOYMENT_TARGET=12.6
cmake -D CMAKE_BUILD_TYPE=Release -D GLFW_NATIVE_API=1 -D CMAKE_OSX_ARCHITECTURES="x86_64;arm64" -D BUILD_SHARED_LIBS=ON -D CMAKE_C_COMPILER=clang ../
make
cp src/libglfw.* ../../
cd ../..
rm -r glfw-${RELEASE} glfw-${RELEASE}.zip